spring:
  application:
    name: orderHub_project

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:orderhub}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8082

logging:
  level:
    org.hibernate.sql: DEBUG
    root: info

management:
  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,500ms,1s,2s

  info:
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  endpoints:
   web:
    exposure:
      include:
        - health
        - info
        - metrics
        - prometheus
        - loggers

info:
  app:
    name: "Order_Hub"
    version: "0.0.1"
    description: "Учимся писать продакшен код"





